apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-serving
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containerConcurrency: 5
      containers:
      - image: serdarkalayci/cloudevents-serving:1.6
